files:
  include:
    - '_dev/scss/**/*.scss'
rules:
  attribute-quotes:
    - 0
  border-zero:
    - 1
    - convention: 'none'
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: false
  class-name-format:
    - 0
  declarations-before-nesting:
    - 2
  empty-args:
    - 1
    - include: true
  empty-line-between-blocks:
    - 0
    - include: true
    - allow-single-line-rulesets: false
  extends-before-declarations:
    - 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-pseudo-nesting:
    - 0
  hex-length:
    - 2
    - style: 'short'
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixins-before-declarations:
    - 0
    - exclude: ['mediaQuery']
  mixin-name-format:
    - 0
  nesting-depth:
    - 2
    - max-depth: 5
  no-color-keywords:
    - 2
  no-color-literals:
    - 0
  no-css-comments:
    - 0
  no-debug:
    - 2
  no-empty-rulesets:
    - 1
  no-extends:
    - 2
  no-important:
    - 0
  no-invalid-hex:
    - 1
  no-misspelled-properties:
    - 1
  no-qualifying-elements:
    - 0
  no-trailing-whitespace:
    - 0
  no-trailing-zero:
    - 2
  no-warn:
    - 2
  property-sort-order:
    - 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes:
    - 2
  variable-name-format:
    - 0
  zero-unit:
    - 2
    - include: false
